### ISSUE TITLE
Please fill in LICENSE in the `opam` file

### ISSUE THREAD

**Issue by sidkshatriya** [leostera/riot#12]
https://github.com/leostera/riot/blob/69540a1a84cab2d467634999053c6772d3cef666/riot.opam#L7

Please do fill in LICENSE in the opam file otherwise opam says

```
[WARNING] Failed checks on riot package definition from source [...]
warning 62: License doesn't adhere to the SPDX standard, see https://spdx.org/licenses/: "LICENSE"
```

BTW I do notice a https://github.com/leostera/riot/blob/main/LICENSE.md file in the repository. So this issue is just to appease `opam`.

**Comment by leostera** [comment]
Done :)
