### ISSUE TITLE
Implement Process Stealing

### ISSUE THREAD

**Issue by leostera** [leostera/riot#30]
As of right now, when processes are scheduled they are put on a random scheduler. This is okay because in the long run we trust the random numbers to evenly distribute across the cores.

However while running a program, most of the time there'll be an unbalance of processes per scheduler. This means that there are processes that could be running that aren't running. And in the cases of apps like [Scarab](https://github.com/leostera/scarab) and [Minttea](https://github.com/leostera/minttea) sometimes a process is so intense that it takes too much time off a scheduler.

We'd like to fix this by allowing schedulers that have no work to steal work from the schedulers that are too busy, and that way seamlessly move the load across cores.

**Implementation Notes**

In short, we should make a few small changes in the `scheduler.ml` (`module Scheduler`):

1. when a scheduler runs out of processes to run, it will call a function to steal a process from the other schedulers, like `steal_processes pool sch max`

2. this function iterates over the `pool.schedulers` and try to grab the next process process queue: (`Proc_queue.next sch.proc_queue`) and move it into its own queue

3. this function should also _lock_ the scheduler into a "stealing" mode so that other schedulers don't steal from it while it is stealing

This is a rather simple strategy but should get us started, and we can refine and add more heuristics as we go.

**Testing Ideas**

Most practical think I can think of here is to make a test that runs a few processes and uses the `Riot.processes ()` function and examines the `Process.sid`, which we'd have to update when we migrate a process from one scheduler to the next.

**Comment by LeedsJohn** [comment]
Hi!  I am hoping that I have a functioning implementation for this feature, but I am stuck on writing a test.  Here is my understanding of how a test could be written:

1.  Spawn 2 processes with the same scheduler (one with high priority, one with low priority)
2. The scheduler should be busy with the high priority process, so a second scheduler should steal the one with low priority.
3. So, the scheduler ID of the low priority process should change at some point.

Is this what you were thinking?

In terms of implementation, I am not sure how I could enforce that two processes use the same scheduler upon creation.

Do you mind giving me advice on how I could implement a test for this feature?

Thank you!

**Comment by leostera** [comment]
Hi John! and thanks for working on this ✨🐫🙏🏼

I think for this test we could have a new version of spawn, say `spawn_pinned`, that instead of getting a random scheduler just uses the current one.

You can find the implementation of spawn in the runtime/import.ml module.

Feel free to open a PR so I can have a look.

(sorry for the lack of links, currently on my phone)

**Comment by leostera** [comment]
Closing this as our first implementation landed with https://github.com/leostera/riot/commit/60d6befe9b6fbe060179f2488613be76b9b898d0
