### ISSUE TITLE
Scheduling on Debian seems not work correctly

### ISSUE THREAD

**Issue by emilpriver** [leostera/riot#6]
I am testing Riot on Debian and I see some issues with the scheduling. When there is 0 job running do the CPU increase to 100% cpu usage but when there is tasks being spammed(many requests at the same time creating tasks) scheduled do it execute the jobs extremly late and the cpu usage drops to 0.1% of usage indicating that there is almost 0 jobs running.
I am running commit d12609a16307acc4b797bd6cabb37aadb05b6090 and did rebuild riot using this commit.

![Skarmavbild_2023-10-11_kl _11 06 22](https://github.com/leostera/riot/assets/34039674/93fcadf9-e66f-4151-8a60-5f00f291ab1b)
I have also sent @leostera a link with a video when i'm testing which shows the behavior.

**Comment by emilpriver** [comment]
This behavior does not exists running on a mac

**Comment by leostera** [comment]
@emilpriver does this still happen on 0.0.4 ?

**Comment by emilpriver** [comment]
Yes, I did try with debian and using https://github.com/leostera/atacama/blob/main/examples/echo.ml to test it. I did also test it in https://orbstack.dev

**Comment by emilpriver** [comment]
Something I did notice was that I got the response on my HTTP call when I did close the server, until I killed my server did I the page only load

**Comment by leostera** [comment]
Thanks @emilpriver 🙏🏼 I need to try that echo server with HTTP calls, it's meant to handle one layer lower, so TCP calls with telnet or nc.

**Comment by leostera** [comment]
@emilpriver i've been building/running riot on ubuntu for the last 2 weeks and since the Gluon rewrite I haven't seen any of these issues. Closing this for now. Feel free to reopen if you think there's something else that needs to be addressed here!
